version = 0.1

[dev.deploy.parameters]
stack_name = "devLepisenseInputApi"
resolve_s3 = false
s3_bucket = "lepisense-lambda"
s3_prefix = "input-api-dev"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "EnvironmentType=\"dev\"" "LogLevel=\"debug\""
image_repositories = []

[test.deploy.parameters]
stack_name = "testLepisenseInputApi"
resolve_s3 = false
s3_bucket = "lepisense-lambda"
s3_prefix = "input-api-test"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "EnvironmentType=\"test\"" "LogLevel=\"info\""
image_repositories = []

[prod.deploy.parameters]
stack_name = "prodLepisenseInputApi"
resolve_s3 = false
s3_bucket = "lepisense-lambda"
s3_prefix = "input-api-prod"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "EnvironmentType=\"prod\"" "LogLevel=\"warning\""
image_repositories = []
